### ISSUE TITLE
用wps2013新建的dps文件时候抛出异常，导致soffice进程直接关闭

### ISSUE THREAD

**Issue by D-luffy** [acmersch/jodconverter4.0#1]
``` java
Oct 25, 2013 9:21:23 AM com.artofsolving.jodconverter.openoffice.connection.AbstractOpenOfficeConnection connect
INFO: connected
Oct 25, 2013 9:21:27 AM com.artofsolving.jodconverter.openoffice.connection.AbstractOpenOfficeConnection disposing
SEVERE: disconnected unexpectedly
Exception in thread "main" com.artofsolving.jodconverter.openoffice.connection.OpenOfficeException: conversion failed: could not load input document
    at com.artofsolving.jodconverter.openoffice.converter.OpenOfficeDocumentConverter.loadAndExport(OpenOfficeDocumentConverter.java:131)
    at com.artofsolving.jodconverter.openoffice.converter.OpenOfficeDocumentConverter.convertInternal(OpenOfficeDocumentConverter.java:120)
    at com.artofsolving.jodconverter.openoffice.converter.AbstractOpenOfficeDocumentConverter.convert(AbstractOpenOfficeDocumentConverter.java:104)
    at com.artofsolving.jodconverter.openoffice.converter.AbstractOpenOfficeDocumentConverter.convert(AbstractOpenOfficeDocumentConverter.java:74)
    at com.artofsolving.jodconverter.openoffice.converter.AbstractOpenOfficeDocumentConverter.convert(AbstractOpenOfficeDocumentConverter.java:70)
    at com.artofsolving.jodconverter.cli.ConvertDocument.convertOne(ConvertDocument.java:154)
    at com.artofsolving.jodconverter.cli.ConvertDocument.main(ConvertDocument.java:133)
Caused by: com.sun.star.lang.DisposedException: java.io.IOException: com.sun.star.io.IOException: EOF reached - socket,host=localhost,port=8100,tcpNoDelay=1,localHost=localhost,localPort=52922,peerHost=localhost,peerPort=8100
    at com.sun.star.lib.uno.bridges.java_remote.java_remote_bridge$MessageDispatcher.run(java_remote_bridge.java:171)
```

**Comment by D-luffy** [comment]
用wps低版本的新建的 dps可以执行成功，wps低版本对应doc的低版本来转换，如果是wps高版本需要用docx来转换。
